#!/bin/sh
# postrm script for eadc-hub
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge|remove)
    rm -rf /usr/lib/eadc-hub || true
    rm -rf /var/log/eadc-hub || true
    rm -rf /var/run/eadc-hub || true

    if [ "$1" = "purge" ]; then
        rm -rf /var/lib/eadc-hub/Mnesia || true
	rmdir -p /var/lib/eadc-hub/Mnesia || true 2>/dev/null
	rm -rf /etc/eadc-hub || true
	update-rc.d eadc-hub remove || true
    fi
    ;;

    *)
        exit 0
    ;;
esac
